//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeachImageWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DraftRecipes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DraftRecipes()
        {
            this.DraftIngredient = new HashSet<DraftIngredient>();
            this.DraftSteps = new HashSet<DraftSteps>();
        }
    
        public int abId { get; set; }
        public string abName { get; set; }
        public Nullable<int> abclassId { get; set; }
        public string abIntroduce { get; set; }
        public byte[] abImg { get; set; }
        public Nullable<int> abQuantity { get; set; }
        public Nullable<int> abTime { get; set; }
        public int cId { get; set; }
    
        public virtual cMember cMember { get; set; }
        public virtual DraftClass DraftClass { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DraftIngredient> DraftIngredient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DraftSteps> DraftSteps { get; set; }
    }
}
